### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by w1zard** [spance/suft#1]
./suftnc -l 9999 -r 2121 -debug 3
panic: runtime error: invalid memory address or nil pointer dereference
ubuntu 14.04 
go version go1.4.2 linux/amd64

**Comment by spance** [comment]
I'm sorry, this is one of my mistakes.

```
./suft-nc -l [addr]:port -r [target]:port [-s] [-b 10] [-fr] < [send_file] > [recv_file]
```

`-l :9999` and `-r server:port`
`-s` for server

**Comment by spance** [comment]
readme updated.
