### ISSUE TITLE
聊天室的例子运行错误

### ISSUE THREAD

**Issue by w1zard** [spance/suft#3]
服务器 23.226.134.xxx
VPS ./suftnc -l :2222 -s -debug 3
2016/02/24 14:08:55.512000 start [::]:2222 <nil>
2016/02/24 14:09:00.568095 send  seq=0 ack=0 scnt=1 len=10
2016/02/24 14:09:00.583653 send  seq=0 ack=0 scnt=1 len=10
2016/02/24 14:09:01.565794 send  seq=0 ack=0 scnt=2 len=10
2016/02/24 14:09:01.566117 send  seq=0 ack=0 scnt=2 len=10
2016/02/24 14:09:01.569247 send  seq=0 ack=0 scnt=2 len=10
2016/02/24 14:09:01.584245 send  seq=0 ack=0 scnt=2 len=10
2016/02/24 14:09:02.565886 send  seq=0 ack=0 scnt=3 len=10
2016/02/24 14:09:02.566006 send  seq=0 ack=0 scnt=3 len=10
2016/02/24 14:09:02.566426 send  seq=0 ack=0 scnt=3 len=10
2016/02/24 14:09:02.566484 send  seq=0 ack=0 scnt=3 len=10
2016/02/24 14:09:02.569475 send  seq=0 ack=0 scnt=3 len=10
2016/02/24 14:09:02.585257 send  seq=0 ack=0 scnt=3 len=10
2016/02/24 14:09:03.565973 send  seq=0 ack=0 scnt=4 len=10
2016/02/24 14:09:03.566097 send  seq=0 ack=0 scnt=4 len=10
2016/02/24 14:09:03.566105 send  seq=0 ack=0 scnt=4 len=10
2016/02/24 14:09:03.566097 send  seq=0 ack=0 scnt=4 len=10
2016/02/24 14:09:03.566575 send  seq=0 ack=0 scnt=4 len=10
2016/02/24 14:09:03.566576 send  seq=0 ack=0 scnt=4 len=10
2016/02/24 14:09:03.569630 send  seq=0 ack=0 scnt=4 len=10
2016/02/24 14:09:03.585474 send  seq=0 ack=0 scnt=4 len=10
2016/02/24 14:09:04.566267 send  seq=0 ack=0 scnt=5 len=10
2016/02/24 14:09:04.566382 send  seq=0 ack=0 scnt=5 len=10
2016/02/24 14:09:04.566440 send  seq=0 ack=0 scnt=5 len=10
2016/02/24 14:09:04.566495 send  seq=0 ack=0 scnt=5 len=10
2016/02/24 14:09:04.566578 send  seq=0 ack=0 scnt=5 len=10
2016/02/24 14:09:04.566736 send  seq=0 ack=0 scnt=5 len=10
2016/02/24 14:09:04.566806 send  seq=0 ack=0 scnt=5 len=10
2016/02/24 14:09:04.569472 send  seq=0 ack=0 scnt=5 len=10
2016/02/24 14:09:04.570183 send  seq=0 ack=0 scnt=5 len=10
2016/02/24 14:09:04.585698 send  seq=0 ack=0 scnt=5 len=10
2016/02/24 14:09:05.566070 send  seq=0 ack=0 scnt=6 len=10
2016/02/24 14:09:05.566226 send  seq=0 ack=0 scnt=6 len=10
2016/02/24 14:09:05.566539 send  seq=0 ack=0 scnt=6 len=10
2016/02/24 14:09:05.566627 send  seq=0 ack=0 scnt=6 len=10
2016/02/24 14:09:05.566685 send  seq=0 ack=0 scnt=6 len=10
2016/02/24 14:09:05.566763 send  seq=0 ack=0 scnt=6 len=10
2016/02/24 14:09:05.566838 send  seq=0 ack=0 scnt=6 len=10
2016/02/24 14:09:05.566884 send  seq=0 ack=0 scnt=6 len=10
2016/02/24 14:09:05.566914 send  seq=0 ack=0 scnt=6 len=10
2016/02/24 14:09:05.569654 send  seq=0 ack=0 scnt=6 len=10
Error init_connection Too many attempts to connect
Error init_connection Too many attempts to connect
2016/02/24 14:09:06.566341 send  seq=0 ack=0 scnt=7 len=10
2016/02/24 14:09:06.566397 send  seq=0 ack=0 scnt=7 len=10
2016/02/24 14:09:06.566837 send  seq=0 ack=0 scnt=7 len=10
2016/02/24 14:09:06.566892 send  seq=0 ack=0 scnt=7 len=10
Error init_connection Too many attempts to connect
2016/02/24 14:09:06.566938 send  seq=0 ack=0 scnt=7 len=10
2016/02/24 14:09:06.566995 send  seq=0 ack=0 scnt=7 len=10
Error init_connection Too many attempts to connect
2016/02/24 14:09:06.567144 send  seq=0 ack=0 scnt=7 len=10
2016/02/24 14:09:06.569933 send  seq=0 ack=0 scnt=7 len=10
2016/02/24 14:09:07.566698 send  seq=0 ack=0 scnt=8 len=10
2016/02/24 14:09:07.566698 send  seq=0 ack=0 scnt=8 len=10
2016/02/24 14:09:07.567096 send  seq=0 ack=0 scnt=8 len=10
2016/02/24 14:09:07.567131 send  seq=0 ack=0 scnt=8 len=10
Error init_connection Too many attempts to connect
2016/02/24 14:09:07.567175 send  seq=0 ack=0 scnt=8 len=10
Error init_connection Too many attempts to connect
2016/02/24 14:09:07.570174 send  seq=0 ack=0 scnt=8 len=10
2016/02/24 14:09:08.567063 send  seq=0 ack=0 scnt=9 len=10
2016/02/24 14:09:08.567063 send  seq=0 ack=0 scnt=9 len=10
2016/02/24 14:09:08.567509 send  seq=0 ack=0 scnt=9 len=10
Error init_connection Too many attempts to connect
Error init_connection Too many attempts to connect
2016/02/24 14:09:08.570426 send  seq=0 ack=0 scnt=9 len=10
2016/02/24 14:09:09.567462 send  seq=0 ack=0 scnt=10 len=10
2016/02/24 14:09:09.567588 send  seq=0 ack=0 scnt=10 len=10
Error init_connection Too many attempts to connect
Error init_connection Too many attempts to connect
Error init_connection Too many attempts to connect
Error init_connection Too many attempts to connect

客户端内网机器
suft-nc.exe -l :9999 -r 23.226.134.xxx:2222 -debug 2
2016/02/24 14:09:00.429307 start 0.0.0.0:9999 <nil>
2016/02/24 14:09:06.430307 connected to 23.226.134.xxx:2222 Too many attempts to connect

**Comment by w1zard** [comment]
多IP 没指定IP的问题

**Comment by spance** [comment]
经过实地测试，发现是使用net_speed做了ip层重复发包造成的，去掉后重新测试，结果如下：

接收端log
![image](https://cloud.githubusercontent.com/assets/3322424/13282851/f70893a2-db25-11e5-9c1b-f1fe59269155.png)

发送端log
![image](https://cloud.githubusercontent.com/assets/3322424/13282856/fc9eb972-db25-11e5-8c28-98b3afd28b8d.png)

接收端流量
![image](https://cloud.githubusercontent.com/assets/3322424/13282862/0152384a-db26-11e5-83a5-593905e2660c.png)

发送端重发率14%
接收端重收率0.09%
发送和接收速度约2M/s
链路丢包率12.6% 属高延迟中度丢包
