### ISSUE TITLE
win客户端咋办？

### ISSUE THREAD

**Issue by kmahyyg** [spance/suft#4]
RT
很抱歉没有能力弄个PR

对Go我直接就不会
希望改进。

**Comment by spance** [comment]
go能够支持包括win在内众多的平台架构和系统，这也是用go做实现的原因。
windows下直接编译就好了，其它平台交叉编译也可以，你说的win客户端是什么意思？

**Comment by kmahyyg** [comment]
我的意思是就是说做成像goagent和ss(cli)那样的，最好能够直接给小白用户调用。

在 2016年2月25日 下午5:20，Spance notifications@github.com写道：

> go能够支持包括win在内众多的平台架构和系统，这也是用go做实现的原因。
> windows下直接编译就好了，你说的win客户端是什么意思？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spance/suft/issues/4#issuecomment-188686017.

## 

Send From My Google Mail

Contact Me:

Twitter:@PotatoOnline
Facebook:Find"Yang Yuguang" (yang.yuguang.73@facebook.com)
QQ:920337808
Tencent Microblog:@kmahyyg @lyxyjg
G+:kmahyygyyg@gmail.com

**Comment by spance** [comment]
suft这个项目只是一个传输协议，提供api给上层应用调用，任何人都可以基于suft开发应用。
另外，由于suft还没有足够大量的测试，因此目前我们也只做了suft-nc这个工具来测试验证协议，以后可能做suft-xxx面向一般用户直接使用。
如果你乐意，可以把suft-nc测试结果分享出来，供我们参考。

**Comment by kmahyyg** [comment]
Thanks.Close #4

在 2016年2月27日 下午9:08，Spance notifications@github.com写道：

> suft这个项目只是一个传输协议，提供api给上层应用调用，任何人都可以基于suft开发应用。
> 另外，由于suft还没有足够大量的测试，因此目前我们也只做了suft-nc这个工具来测试验证协议，以后可能做suft-xxx面向一般用户直接使用。
> 如果你乐意，可以把suft-nc测试结果分享出来，供我们参考。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spance/suft/issues/4#issuecomment-189635845.

## 

Send From My Google Mail

Contact Me:

Twitter:@PotatoOnline
Facebook:Find"Yang Yuguang" (yang.yuguang.73@facebook.com)
QQ:920337808
Tencent Microblog:@kmahyyg @lyxyjg
G+:kmahyygyyg@gmail.com
