### ISSUE TITLE
怎么用来转发ss

### ISSUE THREAD

**Issue by dapao9999** [spance/suft#6]
编译了个，传文件很快很稳定，能转发ss吗

**Comment by spance** [comment]
可以用来转发tcp流，前几天看到已经有人写了转发了 @messyidea
或者也可以自己实现，本质上是一个反向代理，双向流拷贝，百十行就可以基本解决。
不过需要注意，suft层不负责维持心跳，如果在nat后，上层应用就需要维持一定频率的心跳。
